FROM		debian:buster
RUN			apt-get update \
			&& apt-get install -y vim \
			&& apt-get install -y man \
			&& apt-get install -y curl \
			&& apt-get install -y wget \
		  	&& apt-get install -y nginx

